services:
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.9.0
    hostname: wazuh.indexer
    container_name: wazuh.indexer
    restart: always
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=wazuh.indexer
      - cluster.initial_cluster_manager_nodes=wazuh.indexer
      - discovery.type=single-node
      - config.yml=/usr/share/wazuh-indexer/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./wazuh-certificates:/usr/share/wazuh-indexer/config/certs:ro
    ports:
      - "9200:9200"

  wazuh.manager:
    image: wazuh/wazuh-manager:4.9.0
    hostname: wazuh.manager
    container_name: wazuh.manager
    restart: always
    depends_on:
      - wazuh.indexer
    environment:
      - WAZUH_INDEXER_HOSTS=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
    volumes:
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - ./wazuh-certificates:/var/ossec/etc/certs:ro
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    hostname: wazuh.dashboard
    container_name: wazuh.dashboard
    restart: always
    ports:
      - "8443:5601"
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
    volumes:
      - ./wazuh-certificates:/usr/share/wazuh-dashboard/config/certs:ro
    depends_on:
      - wazuh.indexer

volumes:
  wazuh-indexer-data:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
